name: CI
on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.8.0'
                  
    - name: Set environment variables
      run: |
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DBNAME=${{ secrets.DBNAME }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Start the application
    - name: Start the application
      run: npm start
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DBNAME: ${{ secrets.DBNAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PASS: ${{ secrets.DB_PASS }}